spring:
  application:
    name: transport-issue-reporting-platform

  docker:
    compose:
      file: "../docker-compose.yaml"

  datasource:
    url: jdbc:postgresql://localhost:5434/tirp
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop