spring:
  application:
    name: transport-issue-reporting-platform
  docker:
    compose:
      file: ../docker-compose.yaml
  datasource:
    url: jdbc:postgresql://localhost:5434/tirp
    username: postgres
    password: password

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop



# TODO: turn on in prod
#springdoc:
#  swagger-ui:
#      enabled: false